'use client';

import { ArrowLeft, Bot, Check, Home, Scale, Sparkles, X } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { InternalLink as Link } from '@/components/internal-link';
import { useComparisons } from '@/hooks/use-comparisons';
import { useComparisonAnalysis } from '@/hooks/use-comparison-analysis';
import { formatPriceMillions } from '@/lib/marketplace';

export default function ComparePage() {
  const { items, error, toggle } = useComparisons();
  const ai = useComparisonAnalysis();
  return <main className="compare-page">
    <header className="detail-header"><Link className="catalog-brand" href="/"><span><Home /></span>Estate<em>Hub</em></Link><nav><Link href="/catalog?market=all">Купить</Link><Link href="/catalog?market=primary">Новостройки</Link><Link href="/catalog?market=secondary">Вторичный рынок</Link></nav><Link href="/profile">Профиль</Link></header>
    <section className="compare-shell">
      <Link className="compare-back" href="/catalog"><ArrowLeft /> Вернуться в каталог</Link>
      <div className="compare-heading"><div><span><Scale /> Подбор по параметрам</span><h1>Сравнение квартир</h1><p>До четырёх реальных предложений: цены и характеристики берутся из опубликованного реестра.</p></div><strong>{items.length} / 4</strong></div>
      {items.length >= 2 && <section className="ai-comparison-panel"><div className="ai-comparison-heading"><span><Bot /></span><div><small>Объяснимое сравнение</small><h2>AI покажет различия без субъективного «лучше»</h2><p>Цена, площадь и готовность берутся из опубликованных объявлений.</p></div><Button onClick={() => void ai.run()} disabled={ai.loading}><Sparkles /> {ai.loading ? 'Сравниваем…' : ai.analysis ? 'Обновить выводы' : 'Сравнить с AI'}</Button></div>{ai.error && <p className="ai-comparison-error">{ai.error}</p>}{ai.analysis && <><p className="ai-comparison-summary">{ai.analysis.summary}</p><div className="ai-insight-grid">{ai.analysis.insights.map((insight) => <article key={insight.id}><strong>{insight.title}</strong><p>{insight.text}</p><small>Источник: {insight.sourceFields.join(', ')}</small></article>)}</div><div className="ai-tradeoff-grid">{items.map((item) => { const tradeoff = ai.analysis?.tradeoffs.find((entry) => entry.listingId === item.id); return <article key={item.id}><h3>{item.complex_name} · № {item.unit_number}</h3>{tradeoff?.advantages.map((text) => <p className="positive" key={text}><Check /> {text}</p>)}{tradeoff?.tradeoffs.map((text) => <p key={text}>— {text}</p>)}{tradeoff?.missingData.map((text) => <small key={text}>Нет данных: {text}</small>)}</article>; })}</div><p className="ai-guardrail">{ai.analysis.guardrail}</p></>}</section>}
      {error ? <div className="compare-empty"><strong>{error}</strong><Button variant="outline" nativeButton={false} render={<Link href="/catalog" />}>В каталог</Button></div> : items.length === 0 ? <div className="compare-empty"><Scale /><h2>Добавьте квартиры для сравнения</h2><p>Откройте ЖК, выберите «Сравнить» у подходящей квартиры — можно добавить до четырёх вариантов.</p><Button nativeButton={false} render={<Link href="/catalog" />}>Открыть каталог</Button></div> : <div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Параметр</th>{items.map((item) => <th key={item.id}><button type="button" onClick={() => void toggle(item.id)} aria-label={`Убрать квартиру ${item.unit_number}`}><X /></button><img src={item.image} alt=""/><Link href={`/complex/${item.slug}`}>{item.complex_name}</Link><small>Квартира № {item.unit_number}</small></th>)}</tr></thead><tbody><tr><th>Цена</th>{items.map((item) => <td key={item.id}><strong>{formatPriceMillions(item.price_uzs)} сум</strong></td>)}</tr><tr><th>Цена за м²</th>{items.map((item) => <td key={item.id}>{new Intl.NumberFormat('ru-RU').format(item.price_per_sqm)} сум</td>)}</tr><tr><th>Комнаты</th>{items.map((item) => <td key={item.id}>{item.rooms}</td>)}</tr><tr><th>Площадь</th>{items.map((item) => <td key={item.id}>{item.area_sqm} м²</td>)}</tr><tr><th>Этаж</th>{items.map((item) => <td key={item.id}>{item.floor_number} / {item.total_floors}</td>)}</tr><tr><th>Отделка</th>{items.map((item) => <td key={item.id}>{item.finish}</td>)}</tr><tr><th>Продавец</th>{items.map((item) => <td key={item.id}>{item.seller_type === 'developer' ? 'Застройщик' : item.seller_type === 'owner' ? 'Собственник' : 'Агентство'} · {item.seller_verification === 'verified' ? 'проверен' : 'проверяется'}</td>)}</tr><tr><th>Готовность ЖК</th>{items.map((item) => <td key={item.id}>{item.completion_label}</td>)}</tr><tr><th>Онлайн-бронь</th>{items.map((item) => <td key={item.id}>{item.reserve_enabled ? <span className="compare-yes"><Check /> Доступна</span> : 'Нет'}</td>)}</tr><tr><th>Действие</th>{items.map((item) => <td key={item.id}><Link href={`/complex/${item.slug}`}>Открыть ЖК</Link></td>)}</tr></tbody></table></div>}
    </section>
  </main>;
}
