'use client';

import { Check, Flag, MessageSquareText, RotateCcw, ShieldCheck, Star, X } from 'lucide-react';

import { AdminReview } from '@/hooks/use-admin-reviews';

export function AdminReviewsPanel({ reviews, stats, loading, error, processing, onDecision }: { reviews: AdminReview[]; stats: { pending: number; published: number; hidden: number; reports: number }; loading: boolean; error: string; processing: string; onDecision: (id: string, decision: 'publish' | 'reject' | 'hide' | 'restore' | 'dismiss_report', reason?: string) => Promise<void> }) {
  const decide = async (review: AdminReview, decision: 'publish' | 'reject' | 'hide' | 'restore' | 'dismiss_report') => { let reason = ''; if (decision === 'reject' || decision === 'hide') { reason = window.prompt(decision === 'hide' ? 'Почему отзыв нужно скрыть?' : 'Почему отзыв отклонён?')?.trim() ?? ''; if (!reason) return; } await onDecision(review.id, decision, reason); };
  return <section className="admin-panel admin-reviews-panel" id="reviews"><div className="admin-panel-heading"><div><h2>Модерация отзывов</h2><p>Публикация, жалобы и неизменяемый журнал решений</p></div><span className="queue-total">{stats.pending} новых · {stats.reports} жалоб</span></div>{error && <div className="admin-inline-error">{error}</div>}<div className="admin-review-list">{loading ? <div className="table-empty-state">Загружаем отзывы…</div> : reviews.length ? reviews.map((review)=><article key={review.id}><header><span><MessageSquareText/></span><div><strong>{review.author}</strong><small>{review.complex_name} · {review.trust_level === 'verified_resident' ? 'проверенный житель' : 'стандартный отзыв'}</small></div><b>{Number(review.overall).toFixed(1)} <Star/></b></header><p>{review.body}</p>{Number(review.report_count) > 0 && <div className="admin-review-report"><Flag/><span><strong>{review.report_count} жалоб</strong><small>{review.latest_report_reason}</small></span></div>}<footer>{review.status === 'submitted' ? <><button className="approve" type="button" disabled={processing===review.id} onClick={()=>void decide(review,'publish')}><Check/> Опубликовать</button><button className="reject" type="button" disabled={processing===review.id} onClick={()=>void decide(review,'reject')}><X/> Отклонить</button></> : Number(review.report_count)>0 ? <><button className="approve" type="button" disabled={processing===review.id} onClick={()=>void decide(review,'dismiss_report')}><ShieldCheck/> Оставить</button><button className="reject" type="button" disabled={processing===review.id} onClick={()=>void decide(review,'hide')}><X/> Скрыть</button></> : <button type="button" disabled={processing===review.id} onClick={()=>void decide(review,'restore')}><RotateCcw/> Восстановить</button>}</footer></article>) : <div className="table-empty-state">Очередь отзывов и жалоб пуста.</div>}</div></section>;
}
