'use client';

import { Bell, BellRing, CalendarDays, Check, CheckCheck, MessageCircle, ShieldCheck, Sparkles, Tag, WalletCards } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { InternalLink as Link } from '@/components/internal-link';
import { BuyerNotification, BuyerNotificationPreferences } from '@/hooks/use-notifications';

function date(value: string) { return new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(`${value.replace(' ', 'T')}Z`)); }
function EventIcon({ type }: { type: string }) { if (type.includes('message')) return <MessageCircle/>; if (type.includes('viewing')) return <CalendarDays/>; if (type.includes('reservation') || type.includes('refund')) return <WalletCards/>; if (type.includes('price')) return <Tag/>; if (type.includes('offer') || type.includes('inventory') || type.includes('search')) return <Sparkles/>; if (type.includes('verification') || type.includes('review')) return <ShieldCheck/>; return <Bell/>; }

export function NotificationCenter({ notifications, unreadCount, preferences, channelStatus, loading, processing, error, feedback, onRead, onReadAll, onPreferences }: { notifications: BuyerNotification[]; unreadCount: number; preferences: BuyerNotificationPreferences; channelStatus: { inApp: string; email: string; sms: string; push: string }; loading: boolean; processing: boolean; error: string; feedback: string; onRead: (id: string) => Promise<unknown>; onReadAll: () => Promise<unknown>; onPreferences: (next: BuyerNotificationPreferences) => Promise<unknown> }) {
  const savePreference = (key: keyof BuyerNotificationPreferences, value: boolean) => void onPreferences({ ...preferences, [key]: value });
  return <section className="profile-feature-panel notification-center" id="notifications"><div className="notification-heading"><div><span><BellRing/></span><div><small>События аккаунта</small><h2>Центр уведомлений</h2><p>{unreadCount ? `${unreadCount} непрочитанных событий требуют внимания.` : 'Все события просмотрены.'}</p></div></div>{unreadCount > 0 && <Button variant="outline" size="sm" disabled={processing} onClick={()=>void onReadAll()}><CheckCheck/> Прочитать всё</Button>}</div>{error && <p className="notification-error">{error}</p>}{feedback && <p className="notification-success">{feedback}</p>}<div className="notification-layout"><div className="notification-list">{loading ? <div className="notification-empty">Загружаем события…</div> : notifications.length ? notifications.map((item)=>{ const content = <><span className={`notification-icon ${item.priority}`}><EventIcon type={item.event_type}/></span><div><strong>{item.title}</strong><p>{item.body}</p><small>{date(item.created_at)}</small></div>{item.read_at ? <Check/> : <i/>}</>; return item.href ? <Link href={item.href} className={item.read_at ? 'read' : ''} key={item.id} onClick={()=>{ if(!item.read_at) void onRead(item.id); }}>{content}</Link> : <button type="button" className={item.read_at ? 'read' : ''} key={item.id} onClick={()=>{ if(!item.read_at) void onRead(item.id); }}>{content}</button>; }) : <div className="notification-empty"><BellRing/><strong>Новых событий нет</strong><span>Добавьте подписку на ЖК или сохраните поиск.</span></div>}</div><aside className="notification-preferences"><h3>Каналы и согласия</h3><p>In-app работает сразу. Email и SMS находятся в sandbox-очереди до подключения боевых провайдеров.</p><div className="notification-setting"><span><strong>Email</strong><small>{channelStatus.email === 'sandbox_queue' ? 'Sandbox-очередь' : channelStatus.email}</small></span><Switch aria-label="Email-уведомления" checked={preferences.emailEnabled} disabled={processing} onCheckedChange={(checked)=>savePreference('emailEnabled',checked)}/></div><div className="notification-setting"><span><strong>SMS для критических событий</strong><small>{channelStatus.sms === 'sandbox_queue' ? 'Sandbox-очередь' : channelStatus.sms}</small></span><Switch aria-label="SMS для критических событий" checked={preferences.smsCriticalEnabled} disabled={processing} onCheckedChange={(checked)=>savePreference('smsCriticalEnabled',checked)}/></div><div className="notification-setting"><span><strong>Предложения и акции</strong><small>Только с отдельного согласия</small></span><Switch aria-label="Предложения и акции" checked={preferences.marketingConsent} disabled={processing} onCheckedChange={(checked)=>savePreference('marketingConsent',checked)}/></div><div className="notification-audit-note"><Check/> Критические события дедуплицируются и записываются в аудит.</div></aside></div></section>;
}
