export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS regions (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name_ru TEXT NOT NULL,
    name_uz TEXT NOT NULL,
    name_en TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS cities (
    id TEXT PRIMARY KEY,
    region_id TEXT NOT NULL REFERENCES regions(id),
    slug TEXT NOT NULL UNIQUE,
    name_ru TEXT NOT NULL,
    name_uz TEXT NOT NULL,
    name_en TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS districts (
    id TEXT PRIMARY KEY,
    city_id TEXT NOT NULL REFERENCES cities(id),
    slug TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    name_uz TEXT NOT NULL,
    name_en TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(city_id, slug)
  )`,
  `CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    organization_type TEXT NOT NULL CHECK (organization_type IN ('developer', 'agency')),
    verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected', 'suspended')),
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    external_user_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'blocked', 'deleted')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_phone_verifications (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    phone_e164 TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'blocked')),
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS phone_verification_challenges (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    phone_e164 TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS platform_role_assignments (
    user_id TEXT NOT NULL REFERENCES users(id),
    role TEXT NOT NULL CHECK (role IN ('SUPERADMIN', 'PLATFORM_ADMIN', 'MODERATOR', 'VERIFICATION_SPECIALIST', 'FINANCE_OPERATOR', 'SUPPORT', 'CONTENT_MANAGER')),
    assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id, role)
  )`,
  `CREATE TABLE IF NOT EXISTS organization_memberships (
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    role TEXT NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'HEAD_OF_SALES', 'MANAGER', 'CONTENT_MANAGER', 'FINANCE', 'ANALYST')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('invited', 'active', 'suspended', 'removed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(organization_id, user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS verification_cases (
    id TEXT PRIMARY KEY,
    subject_type TEXT NOT NULL CHECK (subject_type IN ('organization', 'owner', 'listing', 'complex')),
    subject_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'submitted', 'in_review', 'approved', 'rejected', 'suspended')),
    risk_level TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high')),
    reviewed_by TEXT,
    reviewed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS complexes (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    district_id TEXT NOT NULL REFERENCES districts(id),
    developer_org_id TEXT NOT NULL REFERENCES organizations(id),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    description TEXT NOT NULL,
    completion_status TEXT NOT NULL CHECK (completion_status IN ('completed', 'under_construction')),
    completion_label TEXT NOT NULL,
    verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected', 'suspended')),
    hero_image_url TEXT NOT NULL,
    featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0, 1)),
    rating REAL NOT NULL DEFAULT 0,
    map_x REAL NOT NULL,
    map_y REAL NOT NULL,
    latitude REAL NOT NULL DEFAULT 39.6542,
    longitude REAL NOT NULL DEFAULT 66.9597,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS complex_publication_workflows (
    complex_id TEXT PRIMARY KEY REFERENCES complexes(id),
    status TEXT NOT NULL CHECK (status IN ('draft', 'submitted', 'in_verification', 'pending_moderation', 'published', 'rejected', 'archived')),
    submitted_at TEXT,
    reviewed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS complex_features (
    id TEXT PRIMARY KEY,
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    category TEXT NOT NULL CHECK (category IN ('infrastructure', 'amenity')),
    name TEXT NOT NULL,
    detail TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(complex_id, category, name)
  )`,
  `CREATE TABLE IF NOT EXISTS buildings (
    id TEXT PRIMARY KEY,
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    name TEXT NOT NULL,
    total_floors INTEGER NOT NULL CHECK (total_floors > 0),
    completion_status TEXT NOT NULL CHECK (completion_status IN ('completed', 'under_construction')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(complex_id, name)
  )`,
  `CREATE TABLE IF NOT EXISTS sections (
    id TEXT PRIMARY KEY,
    building_id TEXT NOT NULL REFERENCES buildings(id),
    name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(building_id, name)
  )`,
  `CREATE TABLE IF NOT EXISTS floors (
    id TEXT PRIMARY KEY,
    section_id TEXT NOT NULL REFERENCES sections(id),
    floor_number INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(section_id, floor_number)
  )`,
  `CREATE TABLE IF NOT EXISTS units (
    id TEXT PRIMARY KEY,
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    building_id TEXT NOT NULL REFERENCES buildings(id),
    section_id TEXT NOT NULL REFERENCES sections(id),
    floor_id TEXT NOT NULL REFERENCES floors(id),
    unit_number TEXT NOT NULL,
    rooms INTEGER NOT NULL CHECK (rooms BETWEEN 1 AND 10),
    area_sqm REAL NOT NULL CHECK (area_sqm > 0),
    floor_number INTEGER NOT NULL,
    total_floors INTEGER NOT NULL,
    finish TEXT NOT NULL,
    availability_status TEXT NOT NULL CHECK (availability_status IN ('available', 'held', 'reserved', 'sold', 'unavailable')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(building_id, unit_number)
  )`,
  `CREATE TABLE IF NOT EXISTS listings (
    id TEXT PRIMARY KEY,
    unit_id TEXT NOT NULL REFERENCES units(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    seller_org_id TEXT REFERENCES organizations(id),
    market_type TEXT NOT NULL CHECK (market_type IN ('PRIMARY_DEVELOPER', 'SECONDARY_OWNER', 'SECONDARY_AGENCY')),
    seller_type TEXT NOT NULL CHECK (seller_type IN ('developer', 'owner', 'agency')),
    price_uzs INTEGER NOT NULL CHECK (price_uzs > 0),
    status TEXT NOT NULL CHECK (status IN ('draft', 'pending_verification', 'pending_moderation', 'published', 'paused', 'reserved', 'sold', 'rejected', 'expired')),
    reserve_enabled INTEGER NOT NULL DEFAULT 0 CHECK (reserve_enabled IN (0, 1)),
    published_at TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS listing_price_history (
    id TEXT PRIMARY KEY,
    listing_id TEXT NOT NULL REFERENCES listings(id),
    old_price_uzs INTEGER,
    new_price_uzs INTEGER NOT NULL CHECK (new_price_uzs > 0),
    reason TEXT NOT NULL,
    changed_by TEXT NOT NULL,
    changed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS media_assets (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('organization', 'complex', 'unit', 'listing')),
    entity_id TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'floor_plan', 'document')),
    url TEXT NOT NULL,
    alt_text TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    actor_type TEXT NOT NULL,
    actor_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS crm_customers (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    buyer_user_id TEXT REFERENCES users(id),
    full_name TEXT NOT NULL,
    phone_e164 TEXT NOT NULL,
    email TEXT,
    first_source TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, phone_e164)
  )`,
  `CREATE TABLE IF NOT EXISTS organization_sales_settings (
    organization_id TEXT PRIMARY KEY REFERENCES organizations(id),
    new_lead_sla_minutes INTEGER NOT NULL DEFAULT 45 CHECK (new_lead_sla_minutes BETWEEN 5 AND 1440),
    sticky_assignment INTEGER NOT NULL DEFAULT 1 CHECK (sticky_assignment IN (0, 1)),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS leads (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES crm_customers(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    listing_id TEXT REFERENCES listings(id),
    lead_type TEXT NOT NULL CHECK (lead_type IN ('consultation', 'viewing', 'reservation', 'chat', 'manual')),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contact_required', 'contacted', 'consultation', 'selection', 'viewing_scheduled', 'viewing_completed', 'reservation', 'deal_in_progress', 'won', 'lost')),
    source TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    repeated_interaction INTEGER NOT NULL DEFAULT 0 CHECK (repeated_interaction IN (0, 1)),
    idempotency_key TEXT NOT NULL UNIQUE,
    lost_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS lead_assignments (
    lead_id TEXT PRIMARY KEY REFERENCES leads(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    assigned_by TEXT NOT NULL REFERENCES users(id),
    assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS viewings (
    id TEXT PRIMARY KEY,
    lead_id TEXT NOT NULL UNIQUE REFERENCES leads(id),
    requested_date TEXT NOT NULL,
    time_slot TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'confirmed', 'rescheduled', 'attended', 'no_show', 'cancelled', 'converted')),
    confirmed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS lead_activities (
    id TEXT PRIMARY KEY,
    lead_id TEXT NOT NULL REFERENCES leads(id),
    actor_type TEXT NOT NULL,
    actor_id TEXT,
    activity_type TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS reservation_transactions (
    id TEXT PRIMARY KEY,
    listing_id TEXT NOT NULL REFERENCES listings(id),
    unit_id TEXT NOT NULL REFERENCES units(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    buyer_user_id TEXT NOT NULL REFERENCES users(id),
    customer_id TEXT NOT NULL REFERENCES crm_customers(id),
    lead_id TEXT NOT NULL UNIQUE REFERENCES leads(id),
    idempotency_key TEXT NOT NULL UNIQUE,
    price_uzs INTEGER NOT NULL CHECK (price_uzs > 0),
    reservation_fee_uzs INTEGER NOT NULL CHECK (reservation_fee_uzs > 0),
    status TEXT NOT NULL CHECK (status IN ('payment_hold', 'confirmed', 'cancelled', 'expired', 'refunded')),
    payment_status TEXT NOT NULL DEFAULT 'awaiting_payment' CHECK (payment_status IN ('awaiting_payment', 'paid', 'refunded', 'failed')),
    hold_expires_at TEXT NOT NULL,
    reservation_expires_at TEXT,
    payment_reference TEXT UNIQUE,
    cancellation_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_favorites (
    user_id TEXT NOT NULL REFERENCES users(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id, complex_id)
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_saved_searches (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    filters_json TEXT NOT NULL,
    notifications_enabled INTEGER NOT NULL DEFAULT 1 CHECK (notifications_enabled IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_recent_views (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    target_type TEXT NOT NULL CHECK (target_type IN ('complex', 'listing')),
    target_id TEXT NOT NULL,
    viewed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, target_type, target_id)
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_watch_subscriptions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    target_type TEXT NOT NULL CHECK (target_type IN ('complex', 'listing', 'saved_search')),
    target_id TEXT NOT NULL,
    notify_price_reduction INTEGER NOT NULL DEFAULT 1 CHECK (notify_price_reduction IN (0, 1)),
    notify_availability INTEGER NOT NULL DEFAULT 1 CHECK (notify_availability IN (0, 1)),
    notify_special_offer INTEGER NOT NULL DEFAULT 1 CHECK (notify_special_offer IN (0, 1)),
    notify_new_inventory INTEGER NOT NULL DEFAULT 1 CHECK (notify_new_inventory IN (0, 1)),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, target_type, target_id)
  )`,
  `CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id TEXT PRIMARY KEY REFERENCES users(id),
    email_enabled INTEGER NOT NULL DEFAULT 1 CHECK (email_enabled IN (0, 1)),
    sms_critical_enabled INTEGER NOT NULL DEFAULT 1 CHECK (sms_critical_enabled IN (0, 1)),
    marketing_consent INTEGER NOT NULL DEFAULT 0 CHECK (marketing_consent IN (0, 1)),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    event_type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    href TEXT,
    entity_type TEXT,
    entity_id TEXT,
    priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'high', 'critical')),
    dedupe_key TEXT NOT NULL,
    read_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, dedupe_key)
  )`,
  `CREATE TABLE IF NOT EXISTS notification_deliveries (
    id TEXT PRIMARY KEY,
    notification_id TEXT NOT NULL REFERENCES notifications(id),
    channel TEXT NOT NULL CHECK (channel IN ('in_app', 'email', 'sms', 'push')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'failed', 'skipped')),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    delivered_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(notification_id, channel)
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_comparisons (
    user_id TEXT NOT NULL REFERENCES users(id),
    listing_id TEXT NOT NULL REFERENCES listings(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id, listing_id)
  )`,
  `CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    buyer_user_id TEXT NOT NULL REFERENCES users(id),
    listing_id TEXT NOT NULL REFERENCES listings(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    organization_id TEXT REFERENCES organizations(id),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(buyer_user_id, listing_id)
  )`,
  `CREATE TABLE IF NOT EXISTS conversation_messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    author_type TEXT NOT NULL CHECK (author_type IN ('buyer', 'seller', 'system')),
    author_user_id TEXT REFERENCES users(id),
    body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 1000),
    read_by_buyer_at TEXT,
    read_by_seller_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS reservation_outcomes (
    reservation_id TEXT PRIMARY KEY REFERENCES reservation_transactions(id),
    outcome_status TEXT NOT NULL DEFAULT 'active' CHECK (outcome_status IN ('active', 'visit_completed', 'deal_in_progress', 'buyer_refused', 'developer_refused', 'sold', 'cancelled_admin')),
    extension_reason TEXT,
    extended_by TEXT REFERENCES users(id),
    extended_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS buyer_identity_verifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE REFERENCES users(id),
    provider TEXT NOT NULL,
    provider_reference TEXT NOT NULL UNIQUE,
    document_type TEXT NOT NULL CHECK (document_type IN ('passport', 'id_card')),
    document_last4 TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'in_review', 'verified', 'rejected')),
    risk_level TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high')),
    rejection_reason TEXT,
    submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by TEXT REFERENCES users(id),
    reviewed_at TEXT,
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS payment_operations (
    id TEXT PRIMARY KEY,
    reservation_id TEXT NOT NULL REFERENCES reservation_transactions(id),
    operation_type TEXT NOT NULL CHECK (operation_type IN ('reservation_payment', 'refund', 'reconciliation')),
    provider TEXT NOT NULL,
    provider_reference TEXT NOT NULL,
    amount_uzs INTEGER NOT NULL CHECK (amount_uzs > 0),
    status TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed', 'manual_review')),
    idempotency_key TEXT NOT NULL UNIQUE,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider, provider_reference, operation_type)
  )`,
  `CREATE TABLE IF NOT EXISTS reservation_disputes (
    id TEXT PRIMARY KEY,
    reservation_id TEXT NOT NULL REFERENCES reservation_transactions(id),
    opened_by_user_id TEXT NOT NULL REFERENCES users(id),
    category TEXT NOT NULL CHECK (category IN ('unit_unavailable', 'terms_not_honored', 'developer_cancelled', 'payment_issue', 'other')),
    description TEXT NOT NULL CHECK (length(description) BETWEEN 20 AND 1000),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_review', 'resolved_refund', 'resolved_no_refund', 'cancelled')),
    priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal', 'high')),
    assigned_to TEXT REFERENCES users(id),
    resolution_note TEXT,
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS subscription_plans (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    inventory_limit INTEGER NOT NULL CHECK (inventory_limit > 0),
    monthly_price_uzs INTEGER NOT NULL DEFAULT 0 CHECK (monthly_price_uzs >= 0),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS developer_subscriptions (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL UNIQUE REFERENCES organizations(id),
    plan_id TEXT NOT NULL REFERENCES subscription_plans(id),
    status TEXT NOT NULL DEFAULT 'trialing' CHECK (status IN ('trialing', 'active', 'past_due', 'cancelled')),
    current_period_start TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_period_end TEXT NOT NULL,
    auto_renew INTEGER NOT NULL DEFAULT 1 CHECK (auto_renew IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS platform_billing_config (
    id TEXT PRIMARY KEY,
    secondary_listing_fee_uzs INTEGER NOT NULL CHECK (secondary_listing_fee_uzs >= 0),
    secondary_period_days INTEGER NOT NULL DEFAULT 30 CHECK (secondary_period_days BETWEEN 1 AND 365),
    updated_by TEXT REFERENCES users(id),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS billing_events (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES organizations(id),
    listing_id TEXT REFERENCES listings(id),
    actor_user_id TEXT REFERENCES users(id),
    event_type TEXT NOT NULL CHECK (event_type IN ('subscription_charge', 'plan_change', 'secondary_purchase', 'secondary_renewal')),
    amount_uzs INTEGER NOT NULL DEFAULT 0 CHECK (amount_uzs >= 0),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
    provider TEXT NOT NULL,
    provider_reference TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS secondary_listing_purchases (
    id TEXT PRIMARY KEY,
    listing_id TEXT NOT NULL REFERENCES listings(id),
    purchaser_user_id TEXT NOT NULL REFERENCES users(id),
    billing_event_id TEXT NOT NULL UNIQUE REFERENCES billing_events(id),
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    price_uzs INTEGER NOT NULL CHECK (price_uzs >= 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'refunded')),
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS developer_subscription_activations (
    billing_event_id TEXT PRIMARY KEY REFERENCES billing_events(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    confirmed_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS secondary_listing_owners (
    listing_id TEXT PRIMARY KEY REFERENCES listings(id),
    seller_user_id TEXT NOT NULL REFERENCES users(id),
    contact_phone TEXT NOT NULL,
    document_type TEXT NOT NULL CHECK (document_type IN ('ownership_certificate', 'power_of_attorney')),
    document_reference TEXT NOT NULL,
    verification_status TEXT NOT NULL DEFAULT 'submitted' CHECK (verification_status IN ('submitted', 'approved', 'rejected')),
    rejection_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS reviews (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    complex_id TEXT NOT NULL REFERENCES complexes(id),
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'published', 'rejected', 'hidden')),
    trust_level TEXT NOT NULL DEFAULT 'standard' CHECK (trust_level IN ('standard', 'verified_resident')),
    moderation_reason TEXT,
    reviewed_by TEXT REFERENCES users(id),
    reviewed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, complex_id)
  )`,
  `CREATE TABLE IF NOT EXISTS review_ratings (
    review_id TEXT NOT NULL REFERENCES reviews(id),
    category TEXT NOT NULL CHECK (category IN ('construction_quality', 'location', 'infrastructure', 'yard', 'sound_insulation', 'management_service')),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    PRIMARY KEY(review_id, category)
  )`,
  `CREATE TABLE IF NOT EXISTS review_responses (
    id TEXT PRIMARY KEY,
    review_id TEXT NOT NULL UNIQUE REFERENCES reviews(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    responder_user_id TEXT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS review_reports (
    id TEXT PRIMARY KEY,
    review_id TEXT NOT NULL REFERENCES reviews(id),
    reporter_user_id TEXT NOT NULL REFERENCES users(id),
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'reviewed', 'dismissed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(review_id, reporter_user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS review_moderation_events (
    id TEXT PRIMARY KEY,
    review_id TEXT NOT NULL REFERENCES reviews(id),
    decision TEXT NOT NULL CHECK (decision IN ('published', 'rejected', 'hidden', 'restored')),
    reason TEXT,
    reviewed_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS promotion_products (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    target_type TEXT NOT NULL CHECK (target_type IN ('complex', 'listing')),
    surface TEXT NOT NULL CHECK (surface IN ('search', 'homepage', 'search_homepage', 'special')),
    duration_days INTEGER NOT NULL CHECK (duration_days BETWEEN 1 AND 365),
    price_uzs INTEGER NOT NULL DEFAULT 0 CHECK (price_uzs >= 0),
    boost_weight INTEGER NOT NULL DEFAULT 0 CHECK (boost_weight BETWEEN 0 AND 1000),
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS promotions (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES promotion_products(id),
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    complex_id TEXT REFERENCES complexes(id),
    listing_id TEXT REFERENCES listings(id),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('scheduled', 'active', 'expired', 'cancelled')),
    starts_at TEXT NOT NULL,
    ends_at TEXT NOT NULL,
    amount_uzs INTEGER NOT NULL DEFAULT 0 CHECK (amount_uzs >= 0),
    provider TEXT NOT NULL,
    provider_reference TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    sponsored_label TEXT NOT NULL DEFAULT 'Реклама',
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((complex_id IS NOT NULL AND listing_id IS NULL) OR (complex_id IS NULL AND listing_id IS NOT NULL))
  )`,
  `CREATE TABLE IF NOT EXISTS support_requests (
    id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    locale TEXT NOT NULL DEFAULT 'ru' CHECK (locale IN ('ru', 'uz', 'en')),
    delivery_status TEXT NOT NULL DEFAULT 'queued' CHECK (delivery_status IN ('queued', 'sent', 'failed')),
    delivery_provider TEXT,
    delivery_reference TEXT,
    delivery_error TEXT,
    source_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS support_request_handling (
    request_id TEXT PRIMARY KEY REFERENCES support_requests(id),
    status TEXT NOT NULL CHECK (status IN ('in_progress', 'answered', 'closed')),
    handled_by TEXT NOT NULL REFERENCES users(id),
    internal_note TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
] as const;

export const indexStatements = [
  `CREATE INDEX IF NOT EXISTS idx_districts_city_id ON districts(city_id)`,
  `CREATE INDEX IF NOT EXISTS idx_complexes_district_status ON complexes(district_id, completion_status)`,
  `CREATE INDEX IF NOT EXISTS idx_complexes_developer_org_id ON complexes(developer_org_id)`,
  `CREATE INDEX IF NOT EXISTS idx_memberships_user_status ON organization_memberships(user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_platform_roles_role ON platform_role_assignments(role)`,
  `CREATE INDEX IF NOT EXISTS idx_phone_challenges_user_created ON phone_verification_challenges(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_phone_challenges_expiry ON phone_verification_challenges(expires_at) WHERE consumed_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_complex_workflow_status ON complex_publication_workflows(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_complex_features_complex_category ON complex_features(complex_id, category, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_units_complex_availability ON units(complex_id, availability_status)`,
  `CREATE INDEX IF NOT EXISTS idx_listings_complex_status ON listings(complex_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_listings_market_price ON listings(market_type, price_uzs) WHERE status = 'published'`,
  `CREATE INDEX IF NOT EXISTS idx_price_history_listing_changed ON listing_price_history(listing_id, changed_at)`,
  `CREATE INDEX IF NOT EXISTS idx_media_entity_sort ON media_assets(entity_type, entity_id, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_verification_subject ON verification_cases(subject_type, subject_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_entity_created ON audit_events(entity_type, entity_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_crm_customers_org_updated ON crm_customers(organization_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_org_status_created ON leads(organization_id, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_customer_created ON leads(customer_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_lead_assignments_organization_user ON lead_assignments(organization_id, user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_viewings_date_status ON viewings(requested_date, status)`,
  `CREATE INDEX IF NOT EXISTS idx_lead_activities_lead_created ON lead_activities(lead_id, created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_one_active_listing ON reservation_transactions(listing_id) WHERE status IN ('payment_hold', 'confirmed')`,
  `CREATE INDEX IF NOT EXISTS idx_reservations_buyer_status ON reservation_transactions(buyer_user_id, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reservations_hold_expiry ON reservation_transactions(status, hold_expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_buyer_favorites_created ON buyer_favorites(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_buyer_saved_searches_updated ON buyer_saved_searches(user_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_buyer_recent_views_user_viewed ON buyer_recent_views(user_id, viewed_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_watch_user_active_updated ON buyer_watch_subscriptions(user_id, active, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_watch_target_active ON buyer_watch_subscriptions(target_type, target_id, active)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created ON notifications(user_id, read_at, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_entity_created ON notifications(entity_type, entity_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_notification_deliveries_status_created ON notification_deliveries(status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_buyer_comparisons_created ON buyer_comparisons(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_buyer_updated ON conversations(buyer_user_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_organization_updated ON conversations(organization_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_conversation_messages_created ON conversation_messages(conversation_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_outcomes_status_updated ON reservation_outcomes(outcome_status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_buyer_identity_status_submitted ON buyer_identity_verifications(status, submitted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_payment_operations_reservation_created ON payment_operations(reservation_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_payment_operations_status_created ON payment_operations(status, created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_reservation_disputes_one_active ON reservation_disputes(reservation_id) WHERE status IN ('open', 'in_review')`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_disputes_status_created ON reservation_disputes(status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_disputes_buyer_created ON reservation_disputes(opened_by_user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_developer_subscriptions_status_end ON developer_subscriptions(status, current_period_end)`,
  `CREATE INDEX IF NOT EXISTS idx_billing_events_org_created ON billing_events(organization_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_billing_events_listing_created ON billing_events(listing_id, created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_offline_payment_reference ON billing_events(provider, provider_reference) WHERE provider IN ('offline_bank_transfer', 'offline_card_transfer')`,
  `CREATE INDEX IF NOT EXISTS idx_secondary_purchases_listing_end ON secondary_listing_purchases(listing_id, period_end)`,
  `CREATE INDEX IF NOT EXISTS idx_secondary_purchases_status_end ON secondary_listing_purchases(status, period_end)`,
  `CREATE INDEX IF NOT EXISTS idx_secondary_owners_user_updated ON secondary_listing_owners(seller_user_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_secondary_owners_verification ON secondary_listing_owners(verification_status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reviews_complex_status_updated ON reviews(complex_id, status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reviews_status_updated ON reviews(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_review_reports_status_created ON review_reports(status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_review_moderation_review_created ON review_moderation_events(review_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_promotions_status_end ON promotions(status, ends_at)`,
  `CREATE INDEX IF NOT EXISTS idx_promotions_org_created ON promotions(organization_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_promotions_complex_status_end ON promotions(complex_id, status, ends_at)`,
  `CREATE INDEX IF NOT EXISTS idx_promotions_listing_status_end ON promotions(listing_id, status, ends_at)`,
  `CREATE INDEX IF NOT EXISTS idx_support_requests_status_created ON support_requests(delivery_status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_support_handling_status_updated ON support_request_handling(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_support_requests_source_created ON support_requests(source_hash, created_at)`,
] as const;
